### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by ellert** [dCache/dcap#23]
I have received a bug report in Debian about that the dcap source contains non-free code:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1029031

The files in question are the source files:

plugins/gssapi/gssTunnel.h
plugins/gssapi/Copyright
plugins/gssapi/tunnelQueue.c
plugins/gssapi/gssIoTunnel.c
plugins/gssapi/tunnelQueue.h

that contain the line

       THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
                 DESY Hamburg DMG-Division

Is this statement correctly reflecting the license status of those files?
If the files are intended to be open source, could the statement be changed and then a new tag be made?

**Comment by kofemann** [comment]
This is obviously an artifacts of the original code, that was later published as LGPLv2. We can (SHOULD) remove those headers.

**Comment by kofemann** [comment]
fixed by #24
