### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by ellert** [dCache/dcap#25]
I'd like to request a new tag.
It is a bit dodgy to change license statements using a patch in packaging.
It would be possible to base the packaging on a git checkout of master of course, but a tagged version would be better. And there are a few other fixes in git that maybe deserve to be part of a tag.
Can the version be bumped in configure.ac and then a tag created?

**Comment by kofemann** [comment]
Hi @ellert ,

this makes sense. New at tag is 2.47.13

https://github.com/dCache/dcap/releases/tag/2.47.13
